"""Shared fixtures for API tests."""
from __future__ import annotations

import io
from collections.abc import Callable
from dataclasses import replace
from pathlib import Path

import pymupdf
import pytest
from app.main import create_app
from fastapi.testclient import TestClient


@pytest.fixture
def client() -> TestClient:
    return TestClient(create_app())


@pytest.fixture
def client_factory() -> Callable[..., TestClient]:
    """Build a TestClient whose settings carry the given overrides.

    Settings are read at create_app() time, so overriding app.state.settings
    right after creation lets a test drive byte-level upload caps, an API
    token, or a rate limit without touching the process environment. Example:
    `client_factory(max_upload_bytes=64 * 1024)` or
    `client_factory(api_token="secret", rate_limit=2)`.
    """

    def _make(**overrides) -> TestClient:
        app = create_app()
        if overrides:
            app.state.settings = replace(app.state.settings, **overrides)
        return TestClient(app)

    return _make


@pytest.fixture
def istqb_pdf() -> Path:
    """The canonical real-world fixture: an ISTQB syllabus committed to the repo
    so the suite is reproducible in CI and on fresh clones."""
    here = Path(__file__).resolve().parent
    p = here / "fixtures" / "istqb-ctal-ta-syllabus-en.pdf"
    assert p.exists(), f"committed fixture missing: {p}"
    return p

@pytest.fixture
def malformed_pdf() -> Path:
    """A minimal PDF whose content stream invokes an XObject absent from its
    resource dict. PyMuPDF parses it but its C runtime emits a non-fatal
    "cannot find XObject resource" warning, the noise #133 captures and silences.
    Generated by `fixtures/_gen_malformed.py`."""
    here = Path(__file__).resolve().parent
    p = here / "fixtures" / "malformed-missing-xobject.pdf"
    assert p.exists(), f"committed fixture missing: {p}"
    return p


@pytest.fixture
def scanned_pdf_bytes() -> bytes:
    Image = pytest.importorskip("PIL.Image")
    ImageDraw = pytest.importorskip("PIL.ImageDraw")
    ImageFont = pytest.importorskip("PIL.ImageFont")

    image = Image.new("RGB", (1200, 400), "white")
    draw = ImageDraw.Draw(image)
    font = ImageFont.load_default(size=72)
    draw.text((80, 140), "OCR BRIDGE SAMPLE", fill="black", font=font)

    png = io.BytesIO()
    image.save(png, format="PNG")

    doc = pymupdf.open()
    try:
        page = doc.new_page(width=612, height=252)
        page.insert_image(page.rect, stream=png.getvalue())
        return doc.tobytes()
    finally:
        doc.close()


@pytest.fixture
def dejavu_font_path() -> Path:
    """Accent-capable TTF committed for the spa-model OCR regression (#204)."""
    here = Path(__file__).resolve().parent
    p = here / "fixtures" / "DejaVuSans.ttf"
    assert p.exists(), f"committed font missing: {p}"
    return p


@pytest.fixture
def scanned_accented_spanish_pdf_bytes(dejavu_font_path: Path) -> bytes:
    """An image-only PDF of accented Spanish, rendered with an accent-capable font
    and given deterministic scan-like softening (#204).

    The softening (downscale/upscale + blur, no RNG so it is byte-reproducible)
    is what exposes the model difference: the `eng` model drops the diacritics
    while `eng+por+spa` recovers them. A clean render or the stock bitmap font
    would not, so this is the fixture that actually proves `spa` is required.
    """
    Image = pytest.importorskip("PIL.Image")
    ImageDraw = pytest.importorskip("PIL.ImageDraw")
    ImageFont = pytest.importorskip("PIL.ImageFont")
    ImageFilter = pytest.importorskip("PIL.ImageFilter")

    w, h = 1800, 320
    image = Image.new("RGB", (w, h), "white")
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype(str(dejavu_font_path), 60)
    draw.text((40, 110), "niño configuración español análisis", fill="black", font=font)

    # Scan-like softening via downscale/upscale + blur (deterministic, no RNG).
    # Counter-intuitively this is what makes the spa model matter: with crisp
    # glyphs every model reads confident ASCII and the accents vanish for all,
    # but under this softening the spa language priors disambiguate toward the
    # accented Spanish forms while eng alone drops them.
    small = image.resize((int(w * 0.55), int(h * 0.55)), Image.BILINEAR)
    image = small.resize((w, h), Image.BILINEAR).filter(ImageFilter.GaussianBlur(1.1))

    png = io.BytesIO()
    image.save(png, format="PNG")

    doc = pymupdf.open()
    try:
        page = doc.new_page(width=w * 0.5, height=h * 0.5)
        page.insert_image(page.rect, stream=png.getvalue())
        return doc.tobytes()
    finally:
        doc.close()


@pytest.fixture
def scanned_spanish_pdf_bytes() -> bytes:
    """An image-only PDF carrying Spanish words, for the auto-language OCR test.

    The words are plain, accent-free, and unambiguously Spanish so a default
    `eng+por+spa` run reads them reliably without depending on accent fidelity.
    """
    Image = pytest.importorskip("PIL.Image")
    ImageDraw = pytest.importorskip("PIL.ImageDraw")
    ImageFont = pytest.importorskip("PIL.ImageFont")

    image = Image.new("RGB", (1400, 400), "white")
    draw = ImageDraw.Draw(image)
    font = ImageFont.load_default(size=64)
    draw.text((60, 160), "INFORME DE PRUEBA DEL DOCUMENTO", fill="black", font=font)

    png = io.BytesIO()
    image.save(png, format="PNG")

    doc = pymupdf.open()
    try:
        page = doc.new_page(width=720, height=206)
        page.insert_image(page.rect, stream=png.getvalue())
        return doc.tobytes()
    finally:
        doc.close()
