"""Shared fixtures for API tests."""
from __future__ import annotations

import io
from pathlib import Path

import pymupdf
import pytest
from app.main import create_app
from fastapi.testclient import TestClient


@pytest.fixture
def client() -> TestClient:
    return TestClient(create_app())


@pytest.fixture
def istqb_pdf() -> Path:
    """The canonical real-world fixture: an ISTQB syllabus committed to the repo
    so the suite is reproducible in CI and on fresh clones."""
    here = Path(__file__).resolve().parent
    p = here / "fixtures" / "istqb-ctal-ta-syllabus-en.pdf"
    assert p.exists(), f"committed fixture missing: {p}"
    return p

@pytest.fixture
def malformed_pdf() -> Path:
    """A minimal PDF whose content stream invokes an XObject absent from its
    resource dict. PyMuPDF parses it but its C runtime emits a non-fatal
    "cannot find XObject resource" warning, the noise #133 captures and silences.
    Generated by `fixtures/_gen_malformed.py`."""
    here = Path(__file__).resolve().parent
    p = here / "fixtures" / "malformed-missing-xobject.pdf"
    assert p.exists(), f"committed fixture missing: {p}"
    return p


@pytest.fixture
def scanned_pdf_bytes() -> bytes:
    Image = pytest.importorskip("PIL.Image")
    ImageDraw = pytest.importorskip("PIL.ImageDraw")
    ImageFont = pytest.importorskip("PIL.ImageFont")

    image = Image.new("RGB", (1200, 400), "white")
    draw = ImageDraw.Draw(image)
    font = ImageFont.load_default(size=72)
    draw.text((80, 140), "OCR BRIDGE SAMPLE", fill="black", font=font)

    png = io.BytesIO()
    image.save(png, format="PNG")

    doc = pymupdf.open()
    try:
        page = doc.new_page(width=612, height=252)
        page.insert_image(page.rect, stream=png.getvalue())
        return doc.tobytes()
    finally:
        doc.close()


@pytest.fixture
def scanned_spanish_pdf_bytes() -> bytes:
    """An image-only PDF carrying Spanish words, for the auto-language OCR test.

    The words are plain, accent-free, and unambiguously Spanish so a default
    `eng+por+spa` run reads them reliably without depending on accent fidelity.
    """
    Image = pytest.importorskip("PIL.Image")
    ImageDraw = pytest.importorskip("PIL.ImageDraw")
    ImageFont = pytest.importorskip("PIL.ImageFont")

    image = Image.new("RGB", (1400, 400), "white")
    draw = ImageDraw.Draw(image)
    font = ImageFont.load_default(size=64)
    draw.text((60, 160), "INFORME DE PRUEBA DEL DOCUMENTO", fill="black", font=font)

    png = io.BytesIO()
    image.save(png, format="PNG")

    doc = pymupdf.open()
    try:
        page = doc.new_page(width=720, height=206)
        page.insert_image(page.rect, stream=png.getvalue())
        return doc.tobytes()
    finally:
        doc.close()
