/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the conversion format pairs
         * @description Returns every format pair md-bridge knows about, shipped or planned, as `{slug, label, source, target, input_mime, output_mime, status, endpoint}`. Shipped pairs carry an `endpoint`; planned pairs have `endpoint: null` and a `status` of `roadmap` or `wanted`.
         */
        get: operations["get_formats_api_formats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service liveness
         * @description Returns `{status: 'ok', version: <semver>}` when the API is up.
         *
         *     Use this for container/orchestrator health checks. Always responds in single-digit milliseconds.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inspect-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inspect a PDF (fonts, sizes, tagged, OCR hint)
         * @description Run cheap diagnostics on a PDF without converting it.
         *
         *     Useful as a pre-flight check before `/api/pdf-to-md` so the UI can warn the
         *     user about scanned PDFs (which need OCR first), show the inferred body font
         *     size, detect PDF/UA tagging, and list the fonts in use.
         *
         *     ### Quick curl example
         *
         *     ```bash
         *     curl -X POST http://localhost:8000/api/inspect-pdf \
         *       -F "file=@whitepaper.pdf"
         *     ```
         *
         *     ### Response
         *
         *     ```json
         *     {
         *       "pages": 4,
         *       "body_size_pt": 11.0,
         *       "heading_sizes_pt": [18.0, 14.0, 12.5],
         *       "fonts": [{"name": "InterRegular", "size": 11.0, "count": 12048, "sample": "Lorem ipsum..."}],
         *       "tagged": true,
         *       "needs_ocr": false
         *     }
         *     ```
         *
         *     `needs_ocr=true` means PyMuPDF extracted very little text per page. The PDF
         *     is almost certainly scanned, so run Tesseract before submitting.
         */
        post: operations["inspect_pdf_api_inspect_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/md-to-docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render a Markdown file into a Word document (.docx)
         * @description Converts Markdown to a deterministic .docx: headings, bold/italic/inline code, lists, block quotes, fenced code, and tables map onto Word elements. Same input, same bytes, every run.
         */
        post: operations["md_to_docx_api_md_to_docx_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/md-to-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render a Markdown file into a PDF
         * @description Render a Markdown file (UTF-8) into a PDF through headless Chromium.
         *
         *     The rendering uses a bundled A4 CSS theme
         *     (`packages/markdown-to-pdf/templates/default.css`).
         *
         *     ### Request
         *
         *     `multipart/form-data`:
         *
         *     | field | required | description |
         *     |---|---|---|
         *     | `file` | yes | A `.md` file (max 500 MB), UTF-8. |
         *     | `options` | no | JSON: `{ "lang": "en" }`. |
         *
         *     ### Response
         *
         *     Binary `application/pdf`. The `Content-Disposition` header carries a
         *     `attachment; filename="<name>.pdf"` hint.
         *
         *     ### Quick curl example
         *
         *     ```bash
         *     curl -X POST http://localhost:8000/api/md-to-pdf \
         *       -F "file=@notes.md" \
         *       --output notes.pdf
         *     ```
         */
        post: operations["md_to_pdf_api_md_to_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pdf-to-md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convert a PDF to structured Markdown
         * @description Extract a structured Markdown document from a PDF.
         *
         *     The conversion is deterministic and heuristic. Headings are detected from
         *     font size and the PDF outline, lists from bullet glyphs, tables from
         *     PyMuPDF's table finder.
         *
         *     ### Request
         *
         *     `multipart/form-data` with two fields:
         *
         *     | field | required | description |
         *     |---|---|---|
         *     | `file` | yes | A `.pdf` file (max 500 MB). |
         *     | `options` | no | JSON string with the keys below. |
         *
         *     ```json
         *     {
         *       "page_break": false,
         *       "with_images": false,
         *       "front_matter": true,
         *       "lang": "en"
         *     }
         *     ```
         *
         *     ### Quick curl example
         *
         *     ```bash
         *     curl -X POST http://localhost:8000/api/pdf-to-md \
         *       -F "file=@whitepaper.pdf" \
         *       -F 'options={"front_matter": true}'
         *     ```
         *
         *     ### Error envelope
         *
         *     Every failure returns:
         *
         *     ```json
         *     { "error": { "code": "<machine_readable>", "message": "<human>", "detail": <optional> } }
         *     ```
         */
        post: operations["pdf_to_md_api_pdf_to_md_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the Markdown → PDF themes
         * @description Returns every registered theme as `{slug, name, description, family}`. Pass a slug as `options.theme` on `POST /api/md-to-pdf` to select it.
         */
        get: operations["get_themes_api_themes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/themes/{slug}/css": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a theme's raw CSS
         * @description Returns the theme's own stylesheet as `text/css` for inline display.
         */
        get: operations["get_theme_css_api_themes__slug__css_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_inspect_pdf_api_inspect_pdf_post */
        Body_inspect_pdf_api_inspect_pdf_post: {
            /**
             * File
             * @description The PDF to inspect.
             */
            file: string;
        };
        /** Body_md_to_docx_api_md_to_docx_post */
        Body_md_to_docx_api_md_to_docx_post: {
            /**
             * File
             * @description The Markdown file to convert.
             */
            file: string;
            /**
             * Options
             * @description Optional JSON string. Example: `{"lang": "en"}`.
             */
            options?: string | null;
        };
        /** Body_md_to_pdf_api_md_to_pdf_post */
        Body_md_to_pdf_api_md_to_pdf_post: {
            /**
             * File
             * @description The Markdown file to render.
             */
            file: string;
            /**
             * Options
             * @description Optional JSON string. Example: `{"lang": "en"}`.
             */
            options?: string | null;
        };
        /** Body_pdf_to_md_api_pdf_to_md_post */
        Body_pdf_to_md_api_pdf_to_md_post: {
            /**
             * File
             * @description The PDF to convert.
             */
            file: string;
            /**
             * Options
             * @description Optional JSON string. Example: `{"page_break": false, "with_images": false, "front_matter": true, "lang": "en"}`.
             */
            options?: string | null;
        };
        /** ConvertStats */
        ConvertStats: {
            /**
             * Bullets
             * @default 0
             */
            bullets: number;
            /**
             * Headings
             * @default 0
             */
            headings: number;
            /**
             * Tables
             * @default 0
             */
            tables: number;
        };
        /** FontUsage */
        FontUsage: {
            /** Count */
            count: number;
            /** Name */
            name: string;
            /** Sample */
            sample: string;
            /** Size */
            size: number;
        };
        /** FormatInfo */
        FormatInfo: {
            /** Endpoint */
            endpoint?: string | null;
            /** Input Mime */
            input_mime: string;
            /** Label */
            label: string;
            /** Output Mime */
            output_mime: string;
            /** Slug */
            slug: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Target */
            target: string;
        };
        /** FrontMatter */
        FrontMatter: {
            /** Author */
            author?: string | null;
            /** Date */
            date?: string | null;
            /** Pages */
            pages?: number | null;
            /** Source */
            source?: string | null;
            /** Title */
            title?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InspectPdfResponse */
        InspectPdfResponse: {
            /** Body Size Pt */
            body_size_pt: number;
            /** Fonts */
            fonts: components["schemas"]["FontUsage"][];
            /** Heading Sizes Pt */
            heading_sizes_pt: number[];
            /** Needs Ocr */
            needs_ocr: boolean;
            /** Pages */
            pages: number;
            /** Tagged */
            tagged: boolean;
        };
        /** PdfToMdResponse */
        PdfToMdResponse: {
            front_matter?: components["schemas"]["FrontMatter"];
            /** Md */
            md: string;
            /**
             * Ocr Applied
             * @default false
             */
            ocr_applied: boolean;
            stats?: components["schemas"]["ConvertStats"];
            /** Warnings */
            warnings?: string[];
        };
        /** ThemeInfo */
        ThemeInfo: {
            /** Description */
            description: string;
            /** Family */
            family: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_formats_api_formats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormatInfo"][];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive and reports its semantic version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "version": "0.1.0"
                     *     }
                     */
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    inspect_pdf_api_inspect_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_inspect_pdf_api_inspect_pdf_post"];
            };
        };
        responses: {
            /** @description Diagnostics about the uploaded PDF. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "body_size_pt": 11,
                     *       "fonts": [
                     *         {
                     *           "count": 12048,
                     *           "name": "InterRegular",
                     *           "sample": "Lorem ipsum...",
                     *           "size": 11
                     *         },
                     *         {
                     *           "count": 320,
                     *           "name": "InterBold",
                     *           "sample": "Introduction",
                     *           "size": 18
                     *         }
                     *       ],
                     *       "heading_sizes_pt": [
                     *         18,
                     *         14,
                     *         12.5
                     *       ],
                     *       "needs_ocr": false,
                     *       "pages": 4,
                     *       "tagged": true
                     *     }
                     */
                    "application/json": components["schemas"]["InspectPdfResponse"];
                };
            };
            /** @description Upload is not a PDF. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upload exceeds the 500 MB cap. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    md_to_docx_api_md_to_docx_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_md_to_docx_api_md_to_docx_post"];
            };
        };
        responses: {
            /** @description Rendered DOCX. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                };
            };
            /** @description Wrong file type or non-UTF-8 markdown. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upload exceeds the 500 MB cap. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed `options` payload. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conversion failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    md_to_pdf_api_md_to_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_md_to_pdf_api_md_to_pdf_post"];
            };
        };
        responses: {
            /** @description Rendered PDF. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": string;
                };
            };
            /** @description Wrong file type. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "wrong_file_type",
                     *         "message": "Expected a Markdown file (.md) but got: notes.txt"
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Upload exceeds the 500 MB cap. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed `options` payload. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Renderer failed (Chromium crashed, missing template, etc). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pdf_to_md_api_pdf_to_md_post: {
        parameters: {
            query?: {
                /** @description Convert even when the PDF has no extractable text layer. Without this, a scanned PDF returns 422 `ocr_required` instead of empty markdown. Use it to bypass a false positive (e.g. an image-only cover). */
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_pdf_to_md_api_pdf_to_md_post"];
            };
        };
        responses: {
            /** @description Successful conversion. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "front_matter": {
                     *         "author": "Author Name",
                     *         "date": "2026-04-12",
                     *         "pages": 4,
                     *         "source": "whitepaper.pdf",
                     *         "title": "Whitepaper"
                     *       },
                     *       "md": "---\\ntitle: \"Whitepaper\"\\npages: 4\\n---\\n\\n# Introduction\\n\\nFirst paragraph...",
                     *       "stats": {
                     *         "bullets": 14,
                     *         "headings": 6,
                     *         "tables": 1
                     *       },
                     *       "warnings": []
                     *     }
                     */
                    "application/json": components["schemas"]["PdfToMdResponse"];
                };
            };
            /** @description Upload is not a PDF. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "wrong_file_type",
                     *         "message": "Expected a PDF file (.pdf) but got: notes.txt"
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Upload exceeds the 500 MB cap. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "payload_too_large",
                     *         "message": "Upload exceeds 500 MB limit."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Malformed `options` payload. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "invalid_options",
                     *         "detail": [
                     *           {
                     *             "loc": [
                     *               "page_break"
                     *             ],
                     *             "msg": "Input should be a valid boolean"
                     *           }
                     *         ],
                     *         "message": "options payload failed validation"
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    get_themes_api_themes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeInfo"][];
                };
            };
        };
    };
    get_theme_css_api_themes__slug__css_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The theme stylesheet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/css": unknown;
                };
            };
            /** @description Unknown theme slug. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "unknown_theme",
                     *         "message": "Theme 'whatever' is not registered."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
